Annotation:
  device: v1007
  language: en-de
  dataset: wmt2014, iwslt, books, bible, laws, medical
  what: transformer, classify
  hyper_parameter: 
  log_file: 

Dataset:
  train_dataset_path:
    - /home/zhengx/data/wmt14_adapt_dataset_share/bible-clean/bible-train.tsv  # iwslt

  train_dataset_domain: [bible]

  dev_dataset_path:
    - /home/zhengx/data/wmt14_adapt_dataset_share/bible-clean/bible-dev.tsv

  dev_dataset_domain: [bible]

  test_dataset_path:
    # - "/home/zhengx/data/wmt2014-ende-share/newstest2013.tsv"
    # - /home/zhengx/data/wmt2014-ende-share/newstest2014.tsv
    - /home/zhengx/data/wmt2014-ende-share/newstest2014.tsv
    - /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/tst2013.tsv
    - /home/zhengx/data/wmt14_adapt_dataset_share/books/books-test.tsv
    - /home/zhengx/data/wmt14_adapt_dataset_share/bible-clean/bible-test.tsv
  
  combine_train_datasets: False
  filter_len: 200

Vocab:
  use_bpe: True
  share_bpe:
  src:
    file: /home/zhengx/data/wmt2014-ende-share/vocab
    max_size: 37000
  trg:
    file: /home/zhengx/data/wmt2014-ende-share/vocab
    max_size: 37000

Model:
  feature_size: 512
  feedforward_dim: 2048
  head_num: 8
  dropout_rate: 0.1
  num_layers: 6
  layer_norm_rescale: True

  share_enc_dec_embedding: True
  share_decoder_embedding: True

  # generator
  generator_bias: False
  
  classifier_type: simple
  kernel_nums: [50, 50, 50]
  kernel_sizes: [3, 4, 5]

  classify_feature_size: 128
  domain_class_num: 10
  domain_mask: [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
  domain_dict: {
    'news': 0,
    'iwslt': 1,
    'books': 2,
    'bible': 3,
  }
  domain_adapter_dict: {
    'iwslt': {
      'memory_count': 256
    },
    'books': {
      'memory_count': 512
    },
    'bible': {
      'memory_count': 1024
    },
  }

Criterion:
  name: cross_entropy
  # name: nll
  # label_smoothing: 0.1
  # reduction: mean

  # name: kl_divergence
  # label_smoothing: 0.1
  # reduction: sum

Optimizer:
  beta2: 0.998
  lr_rate: 5.0e-4
  lr_scheduler:
    name: reduce_lr_on_bleu
    factor: 0.5
    patience: 5
    min_lr: 5.0e-5
  grad_clip: -1.0

Train:
  stage: translate
  target_domain: bible
  use_multiple_gpu: False

  random_seed: 1234
  load_exist_model: True # load model
  model_load_path: /home/zhengx/model_save/classify/mix-emb-part-simple/loss_best/model
  load_optimizer: False  # load model and optimizer
  optimizer_path: 
  load_lr_scheduler: False
  lr_scheduler_path: 

  batch_size: 12000
  update_batch_count: 1
  epoch_num: 1000

Validation:

  batch_size: 64

  loss_validation:
    start_on_steps: 1000
    frequency: 1000
  
  bleu_validation:
    start_on_steps: 1000
    frequency: 1000

    tokenize: intl
    target_language: de
    use_bpe: True
    ref: /home/zhengx/data/wmt14_adapt_dataset_share/bible-clean/bible-dev.de
    detruecase_script: /home/user_data55/zhengx/project/NMT/scripts/recaser/detruecase.perl
    detokenize_script: /home/user_data55/zhengx/project/NMT/scripts/tokenizer/detokenizer.perl

    beam_search:
      beam_size: 4
      max_steps: 150
      length_penalty: True
      alpha: 0.6

Test:

  # model_path: /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale/loss_best/model
  model_path: /home/zhengx/model_save/classify/part/loss_best/model
  # model_path: /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale_inverse_sqrt/loss_best/model
  save_in_multi_gpu: False
  batch_size: 128
  output_path:
    - /home/zhengx/output/classify/news-predict.out
    - /home/zhengx/output/classify/iwslt-predict.out
    - /home/zhengx/output/classify/books-predict.out
    - /home/zhengx/output/classify/bible-predict.out


Record:
  training_record_path: /home/user_data55/zhengx/record/wmt-2-bible/mix-classifier-adapter-1024
  
  model_record:
    path: /home/zhengx/model_save/wmt-2-bible/mix-classifier-adapter-1024
    best_model_save:
      loss_best: False
      bleu_best: True
      save_optimizer: False
      save_lr_scheduler: False
    
    # save last checkpoint
    last_checkpoint_save:
      start_on_steps: 50000
      frequency: 2000
      save_optimizer: False
      save_lr_scheduler: False
      save_checkpoint_count: 0

visualize_file: /home/zhengx/visualize/wmt14_adapt/news
