Annotation:
  device: v1002-2
  language: de-en
  dataset: wmt2015 de-en, clean 50, bpe 32k, vocab 35k
  what: transformer, 
  hyper_parameter: 
  log_file: 

Dataset:
  train_dataset_path:
    - "/home/zhengx/data/IWSLT2015-ende-share/IWSLT15.TED.train2015.en-de.tsv" # bpe size 32000

  dev_dataset_path:
    - "/home/zhengx/data/IWSLT2015-ende-share/IWSLT15.TED.tst2012.en-de.tsv"

  test_dataset_path:
    # - "/home/zhengx/data/IWSLT2015-ende-share/IWSLT15.TED.tst2012.en-de.tsv"
    - "/home/zhengx/data/IWSLT2015-ende-share/IWSLT15.TED.tst2013.en-de.tsv"
    - "/home/zhengx/data/IWSLT2015-ende-share/IWSLT15.TED.tst2014.en-de.tsv"
  
  combine_train_datasets: False
  filter_len: 100

Vocab:
  use_bpe: True
  src:
    file: "/home/zhengx/data/WMT2015-ende-share/vocab.de"
    max_size: 35000
  trg:
    file: "/home/zhengx/data/WMT2015-ende-share/vocab.en"
    max_size: 35000

Model:
  feature_size: 512
  feedforward_dim: 2048
  head_num: 8
  dropout_rate: 0.1
  num_layers: 6
  share_embedding: False
  adapter_domains: ['iwslt']
  adapter_bottleneck_size: 512

Optimizer:
  factor: 2.0
  warmup_step: 8000
  grad_clip: 1.0


Train:
  current_domain: iwslt

  load_exist_model: True # load model
  model_load_path: /home/zhengx/model_save/wmt2015-deen/mt-transformer-3/model/best_model

  load_optimizer: False  # load model and optimizer
  optimizer_path: 

  batch_size: 8096

  epoch_num: 1000
  validation_per_steps: 2000

Validation:
  option: [loss, bleu] # bleu, loss, accuracy
  Decoding:
    beam_size: 4
    max_steps: 120

  batch_size: 80
  Bleu:
    gram: 4
    level: word

Test:
  batch_size: 80
  tag: translation
  Decoding:
    beam_size: 4
    max_steps: 100
  # parameter as validation
  model_path: /home/zhengx/model_save/WMT2015-ende/mt-transformer/model/best_model
  output_path:
    - "/home/zhengx/output/Education-Laws-deen-label/education.output"
    # - "/home/zhengx/output/Education-Laws-deen-label/laws.output"
    # - "../data/finetune-ende/nc-devtest2007.output"

Record:
  path: "/home/user_data55/zhengx/project/record-new/iwslt2015-deen/mt-transformer-adapter-512"
  model_record_path: /home/zhengx/model_save/iwslt2015-deen/mt-transformer-adapter-512
