Annotation:
  - preprocess wmt2014-ende adapt to other domain dataset

# lowercase:
  # - {language: en, dir: /home/zhengx/data/Laws-ende, files: [Laws-train.en, Laws-dev.en, Laws-test.en]}

tokenize:
#   - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/laws, 
#      files: [acquis-train.en, acquis-dev.en, acquis-test.en]}
#   - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/laws, 
#      files: [acquis-train.de, acquis-dev.de, acquis-test.de]}

#   - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/medical, 
#      files: [emea-train.en, emea-dev.en, emea-test.en]}
#   - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/medical, 
#      files: [emea-train.de, emea-dev.de, emea-test.de]}

  - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/laws-clean, 
     files: [laws-train.en, laws-dev.en, laws-test.en]}
  - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/laws-clean, 
     files: [laws-train.de, laws-dev.de, laws-test.de]}

  - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/medical-clean, 
     files: [medical-train.en, medical-dev.en, medical-test.en]}
  - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/medical-clean, 
     files: [medical-train.de, medical-dev.de, medical-test.de]}

  # - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015, 
  #    files: [IWSLT15.TED.train2015.en-de.en, IWSLT15.TED.tst2012.en-de.en, IWSLT15.TED.tst2013.en-de.en, IWSLT15.TED.tst2014.en-de.en, IWSLT15.TEDX.dev2012.en-de.en]}
  # - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015, 
  #    files: [IWSLT15.TED.train2015.en-de.de, IWSLT15.TED.tst2012.en-de.de, IWSLT15.TED.tst2013.en-de.de, IWSLT15.TED.tst2014.en-de.de, IWSLT15.TEDX.dev2012.en-de.de]}

  # - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/it, 
  #    files: [it-train.en, it-dev.en, it-test.en]}
  # - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/it, 
  #    files: [it-train.de, it-dev.de, it-test.de]}

  # - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/koran, 
  #    files: [koran-train.en, koran-dev.en, koran-test.en]}
  # - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/koran, 
  #    files: [koran-train.de, koran-dev.de, koran-test.de]}

#   - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/books, 
#      files: [books-train.en, books-dev.en, books-test.en]}
#   - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/books, 
#      files: [books-train.de, books-dev.de, books-test.de]}

#   - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/kde, 
#      files: [kde-train.en, kde-dev.en, kde-test.en]}
#   - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/kde, 
#      files: [kde-train.de, kde-dev.de, kde-test.de]}

#   - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/php, 
#      files: [php-train.en, php-dev.en, php-test.en]}
#   - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/php, 
#      files: [php-train.de, php-dev.de, php-test.de]}

#   - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/subtitles, 
#      files: [subtitles-train.en, subtitles-dev.en, subtitles-test.en]}
#   - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/subtitles, 
#      files: [subtitles-train.de, subtitles-dev.de, subtitles-test.de]}

#   - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/bible, 
#      files: [bible-train.en, bible-dev.en, bible-test.en]}
#   - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/bible, 
#      files: [bible-train.de, bible-dev.de, bible-test.de]}

#   - {language: en, dir: /home/zhengx/data/wmt14_adapt_dataset/ecb, 
#      files: [ecb-train.en, ecb-dev.en, ecb-test.en]}
#   - {language: de, dir: /home/zhengx/data/wmt14_adapt_dataset/ecb, 
#      files: [ecb-train.de, ecb-dev.de, ecb-test.de]}

clean:
  - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/laws-clean/laws-train.tok}
  - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/medical-clean/medical-train.tok}
  # - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/laws/acquis-train.tok}
  # - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/medical/emea-train.tok}
  # - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.train2015.en-de.tok}
  # - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/it/it-train.tok}
  # - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/koran/koran-train.tok}
#   - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/books/books-train.tok}
#   - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/kde/kde-train.tok}
#   - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/php/php-train.tok}
#   - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/subtitles/subtitles-train.tok}
#   - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/bible/bible-train.tok}
#   - {min_len: 1, max_len: 80, ratio: 9, src_language: en, trg_language: de, file_prefix: /home/zhengx/data/wmt14_adapt_dataset/ecb/ecb-train.tok}


apply_bpe:
  - {code_file: /home/zhengx/data/wmt14_adapt_dataset/code32k,
     dir: /home/zhengx/data/wmt14_adapt_dataset,
     files: [
      #  books/books-train.tok.clean.en,
      #  books/books-train.tok.clean.de,
      #  books/books-dev.tok.en,
      #  books/books-dev.tok.de,
      #  books/books-test.tok.en,
      #  books/books-test.tok.de,
      #  kde/kde-train.tok.clean.en,
      #  kde/kde-train.tok.clean.de,
      #  kde/kde-dev.tok.en,
      #  kde/kde-dev.tok.de,
      #  kde/kde-test.tok.en,
      #  kde/kde-test.tok.de,
      #  php/php-train.tok.clean.en,
      #  php/php-train.tok.clean.de,
      #  php/php-dev.tok.en,
      #  php/php-dev.tok.de,
      #  php/php-test.tok.en,
      #  php/php-test.tok.de,
      #  subtitles/subtitles-train.tok.clean.en,
      #  subtitles/subtitles-train.tok.clean.de,
      #  subtitles/subtitles-dev.tok.en,
      #  subtitles/subtitles-dev.tok.de,
      #  subtitles/subtitles-test.tok.en,
      #  subtitles/subtitles-test.tok.de,
      #  bible/bible-train.tok.clean.en,
      #  bible/bible-train.tok.clean.de,
      #  bible/bible-dev.tok.en,
      #  bible/bible-dev.tok.de,
      #  bible/bible-test.tok.en,
      #  bible/bible-test.tok.de,
      #  ecb/ecb-train.tok.clean.en,
      #  ecb/ecb-train.tok.clean.de,
      #  ecb/ecb-dev.tok.en,
      #  ecb/ecb-dev.tok.de,
      #  ecb/ecb-test.tok.en,
      #  ecb/ecb-test.tok.de,
       laws-clean/laws-train.tok.clean.en,
       laws-clean/laws-train.tok.clean.de,
       laws-clean/laws-dev.tok.en,
       laws-clean/laws-dev.tok.de,
       laws-clean/laws-test.tok.en,
       laws-clean/laws-test.tok.de,
       medical-clean/medical-train.tok.clean.en,
       medical-clean/medical-train.tok.clean.de,
       medical-clean/medical-dev.tok.en,
       medical-clean/medical-dev.tok.de,
       medical-clean/medical-test.tok.en,
       medical-clean/medical-test.tok.de,
      #  it/it-train.tok.clean.en,
      #  it/it-train.tok.clean.de,
      #  it/it-dev.tok.en,
      #  it/it-dev.tok.de,
      #  it/it-test.tok.en,
      #  it/it-test.tok.de,
      #  iwslt2015/IWSLT15.TED.train2015.en-de.tok.clean.en,
      #  iwslt2015/IWSLT15.TED.train2015.en-de.tok.clean.de,
      #  iwslt2015/IWSLT15.TEDX.dev2012.en-de.tok.en,
      #  iwslt2015/IWSLT15.TEDX.dev2012.en-de.tok.de,
      #  iwslt2015/IWSLT15.TED.tst2012.en-de.tok.en,
      #  iwslt2015/IWSLT15.TED.tst2012.en-de.tok.de,
      #  iwslt2015/IWSLT15.TED.tst2013.en-de.tok.en,
      #  iwslt2015/IWSLT15.TED.tst2013.en-de.tok.de,
      #  iwslt2015/IWSLT15.TED.tst2014.en-de.tok.en,
      #  iwslt2015/IWSLT15.TED.tst2014.en-de.tok.de,
      #  koran/koran-train.tok.clean.en,
      #  koran/koran-train.tok.clean.de,
      #  koran/koran-dev.tok.en,
      #  koran/koran-dev.tok.de,
      #  koran/koran-test.tok.en,
      #  koran/koran-test.tok.de,
       ]       
  }

concat:
  - {files: [], obj_file: }

save_tsv:
  - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/laws-clean/laws-train.tok.clean.bpe.en, 
                   trg: /home/zhengx/data/wmt14_adapt_dataset/laws-clean/laws-train.tok.clean.bpe.de}, 
     tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/laws-clean/laws-train.tsv}

  - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/laws-clean/laws-dev.tok.bpe.en, 
                   trg: /home/zhengx/data/wmt14_adapt_dataset/laws-clean/laws-dev.tok.bpe.de}, 
     tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/laws-clean/laws-dev.tsv}

  - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/laws-clean/laws-test.tok.bpe.en, 
                   trg: /home/zhengx/data/wmt14_adapt_dataset/laws-clean/laws-test.tok.bpe.de}, 
     tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/laws-clean/laws-test.tsv}

  - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/medical-clean/medical-train.tok.clean.bpe.en, 
                   trg: /home/zhengx/data/wmt14_adapt_dataset/medical-clean/medical-train.tok.clean.bpe.de}, 
     tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/medical-clean/medical-train.tsv}

  - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/medical-clean/medical-dev.tok.bpe.en, 
                   trg: /home/zhengx/data/wmt14_adapt_dataset/medical-clean/medical-dev.tok.bpe.de}, 
     tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/medical-clean/medical-dev.tsv}

  - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/medical-clean/medical-test.tok.bpe.en, 
                   trg: /home/zhengx/data/wmt14_adapt_dataset/medical-clean/medical-test.tok.bpe.de}, 
     tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/medical-clean/medical-test.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/it/it-train.tok.clean.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/it/it-train.tok.clean.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/it/it-train.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/it/it-dev.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/it/it-dev.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/it/it-dev.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/it/it-test.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/it/it-test.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/it/it-test.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/koran/koran-train.tok.clean.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/koran/koran-train.tok.clean.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/koran/koran-train.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/koran/koran-dev.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/koran/koran-dev.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/koran/koran-dev.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/koran/koran-test.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/koran/koran-test.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/koran/koran-test.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.train2015.en-de.tok.clean.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.train2015.en-de.tok.clean.bpe.de,}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/train2015.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TEDX.dev2012.en-de.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TEDX.dev2012.en-de.tok.bpe.en}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/dev-2012.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.tst2012.en-de.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.tst2012.en-de.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/tst2012.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.tst2013.en-de.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.tst2013.en-de.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/tst2013.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.tst2014.en-de.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/iwslt2015/IWSLT15.TED.tst2014.en-de.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/tst2014.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/books/books-train.tok.clean.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/books/books-train.tok.clean.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/books/books-train.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/books/books-dev.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/books/books-dev.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/books/books-dev.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/books/books-test.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/books/books-test.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/books/books-test.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/php/php-train.tok.clean.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/php/php-train.tok.clean.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/php/php-train.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/php/php-dev.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/php/php-dev.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/php/php-dev.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/php/php-test.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/php/php-test.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/php/php-test.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/kde/kde-train.tok.clean.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/kde/kde-train.tok.clean.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/kde/kde-train.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/kde/kde-dev.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/kde/kde-dev.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/kde/kde-dev.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/kde/kde-test.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/kde/kde-test.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/kde/kde-test.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/subtitles/subtitles-train.tok.clean.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/subtitles/subtitles-train.tok.clean.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/subtitles/subtitles-train.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/subtitles/subtitles-dev.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/subtitles/subtitles-dev.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/subtitles/subtitles-dev.tsv}

  # - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/subtitles/subtitles-test.tok.bpe.en, 
  #                  trg: /home/zhengx/data/wmt14_adapt_dataset/subtitles/subtitles-test.tok.bpe.de}, 
  #    tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/subtitles/subtitles-test.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/bible/bible-train.tok.clean.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/bible/bible-train.tok.clean.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/bible/bible-train.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/bible/bible-dev.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/bible/bible-dev.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/bible/bible-dev.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/bible/bible-test.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/bible/bible-test.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/bible/bible-test.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/ecb/ecb-train.tok.clean.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/ecb/ecb-train.tok.clean.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/ecb/ecb-train.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/ecb/ecb-dev.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/ecb/ecb-dev.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/ecb/ecb-dev.tsv}

#   - {tsv_format: { src: /home/zhengx/data/wmt14_adapt_dataset/ecb/ecb-test.tok.bpe.en, 
#                    trg: /home/zhengx/data/wmt14_adapt_dataset/ecb/ecb-test.tok.bpe.de}, 
#      tsv_path: /home/zhengx/data/wmt14_adapt_dataset_share/ecb/ecb-test.tsv}