Annotation:
  device: v100-1
  language: en-de
  dataset: wmt2014 en-de, iwslt, books, bible, laws, medical
  what: transformer, 
  hyper_parameter: 
  log_file: 

Dataset:
  train_dataset_path:
    - /home/zhengx/data/wmt2014-ende-share/train.tsv  # news
    - /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/train2015.tsv  # iwslt
    - /home/zhengx/data/wmt14_adapt_dataset_share/books/books-train.tsv  # books
    - /home/zhengx/data/wmt14_adapt_dataset_share/bible-clean/bible-train.tsv  # bible
    - /home/zhengx/data/wmt14_adapt_dataset_share/laws-clean/laws-train.tsv  # laws
    - /home/zhengx/data/wmt14_adapt_dataset_share/medical-clean/medical-train.tsv  # medical


  dev_dataset_path:
    - /home/zhengx/data/wmt2014-ende-share/newstest2013.tsv

  test_dataset_path:
    # - "/home/zhengx/data/wmt2014-ende-share/newstest2013.tsv"
    - "/home/zhengx/data/wmt2014-ende-share/newstest2014.tsv"
  
  combine_train_datasets: True
  filter_len: 200

Vocab:
  use_bpe: True
  share_bpe:
  src:
    file: /home/zhengx/data/wmt2014-ende-share/vocab
    max_size: 37000
  trg:
    file: /home/zhengx/data/wmt2014-ende-share/vocab
    max_size: 37000

Model:
  feature_size: 512
  feedforward_dim: 2048
  head_num: 8
  dropout_rate: 0.1
  num_layers: 6
  layer_norm_rescale: True

  share_enc_dec_embedding: True
  share_decoder_embedding: True

  # generator
  generator_bias: False

Criterion:
  # name: nll
  # label_smoothing: 0.1
  # reduction: mean

  name: kl_divergence
  label_smoothing: 0.1
  reduction: sum

Optimizer:
  beta2: 0.998
  lr_rate: 1.0e-7
  lr_scheduler:
    name: noam
    factor: 2.0
    warmup_steps: 8000
    model_size: 512
    # name: inverse_sqrt
    # warmup_steps: 4000
    # init_lr: 1.0e-7
    # max_lr: 0.0007
    # min_lr: 1.0e-9
  grad_clip: -1.0

Train:
  use_multiple_gpu: False

  random_seed: 1234
  load_exist_model: False # load model
  model_load_path: 
  load_optimizer: False  # load model and optimizer
  optimizer_path: 
  load_lr_scheduler: False
  lr_scheduler_path: 

  batch_size: 12000
  update_batch_count: 2
  epoch_num: 50

Validation:
  
  batch_size: 64

  loss_validation:
    start_on_steps: 1000
    frequency: 500
  
  bleu_validation:
    start_on_steps: 10000
    frequency: 1000

    tokenize: intl
    target_language: de
    use_bpe: True
    ref: /home/zhengx/data/wmt2014-ende-share/newstest2013.de
    detruecase_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/recaser/detruecase.perl
    detokenize_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/tokenizer/detokenizer.perl

    beam_search:
      beam_size: 4
      max_steps: 150
      length_penalty: True
      alpha: 0.6

Test:

  refs: [
    # /home/zhengx/data/wmt2014-ende-share/newstest2013.de,
    /home/zhengx/data/wmt2014-ende-share/newstest2014.de
  ]
  
  # model_path: /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale/loss_best/model
  model_path: /home/zhengx/model_save/entire-ende/no_layer_norm_rescale/bleu_best/model
  # model_path: /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale_inverse_sqrt/loss_best/model
  save_in_multi_gpu: False
  
  output_path:
    # - "/home/zhengx/output/wmt2014-ende/newstest2013.output"
    - "/home/zhengx/output/wmt2014-ende/newstest2014.output"

  tokenize: intl
  target_language: de
  use_bpe: True
  detruecase_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/recaser/detruecase.perl
  detokenize_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/tokenizer/detokenizer.perl

  batch_size: 128
  tag: translation

  beam_search:
    beam_size: 4
    max_steps: 150
    length_penalty: True
    alpha: 0.6


Record:
  training_record_path: /home/user_data55/zhengx/record/entire-ende/no_layer_norm_rescale
  
  model_record:
    path: /home/zhengx/model_save/entire-ende/no_layer_norm_rescale
    best_model_save:
      loss_best: True
      bleu_best: True
      save_optimizer: False
      save_lr_scheduler: False
    
    # save last checkpoint
    last_checkpoint_save:
      start_on_steps: 50000
      frequency: 2000
      save_optimizer: False
      save_lr_scheduler: False
      save_checkpoint_count: 5

AverageModel:
  model_name: transformer
  save_in_multi_gpu: False
  load_path:
    # - /home/zhengx/model_save/wmt2014-ende/6000-4/loss_best/model
    -  /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale/checkpoint0/model
    -  /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale/checkpoint1/model
    -  /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale/checkpoint2/model
    -  /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale/checkpoint3/model
    -  /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale/checkpoint4/model
  save_path: /home/zhengx/model_save/wmt14-ende/no_layer_norm_rescale/average_best_model

visualize_file: /home/zhengx/visualize/wmt14_adapt/news
