Annotation:
  device: 
  dataset: 
  what:  
  model: transformer layer 6 head 4 dim 1024 drop 0.3
  hyper_parameter: warm step 4000, batch size 4096, 
  log_file: 
  comment: 

Dataset:
  train_dataset_path:
    - "/home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/train2015.tsv" # bpe size 32000

  dev_dataset_path:
    - "/home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/tst2012.tsv"

  test_dataset_path:
    - "/home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/tst2013.tsv"
    - "/home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/tst2014.tsv"

  combine_train_datasets: False
  filter_len: 200

Vocab:
  use_bpe: True
  src:
    file: "/home/zhengx/data/wmt14_adapt_dataset_share/vocab"
    max_size: 37000
  trg:
    file: "/home/zhengx/data/wmt14_adapt_dataset_share/vocab"
    max_size: 37000

Model:
  feature_size: 512
  feedforward_dim: 1024
  head_num: 4
  dropout_rate: 0.3
  num_layers: 6

  share_enc_dec_embedding: True
  share_decoder_embedding: True

  # generator
  generator_bias: False

Criterion:
  # name: nll
  # label_smoothing: 0.1
  # reduction: mean

  name: kl_divergence
  label_smoothing: 0.1
  reduction: sum

Optimizer:
  beta2: 0.998
  lr_rate: 5.0e-4
  lr_scheduler:
    name: inverse_sqrt
    factor: 2.0
    warmup_steps: 4000
    init_lr: 1.0e-7
    max_lr: 5.0e-4
    min_lr: 1.0e-7
    # model_size: 512
    # name: noam
    # factor: 2.0
    # warmup_steps: 4000
    # model_size: 512
    # name: reduce_lr_on_loss
    # factor: 0.5
    # patience: 2
    # min_lr: 5.0e-6
  grad_clip: -1.0


Train:
  use_multiple_gpu: False

  random_seed: 1234
  load_exist_model: False # load model
  model_load_path: /home/zhengx/model_save/wmt14-2-education/finetune-update/bleu_best/model
  load_optimizer: False  # load model and optimizer
  optimizer_path:
  load_lr_scheduler: False
  lr_scheduler_path:

  batch_size: 4096
  update_batch_count: 1
  epoch_num: 100

Validation:
  
  batch_size: 24

  loss_validation:
    start_on_steps: 1000
    frequency: 1000
  
  bleu_validation:
    start_on_steps: 1000
    frequency: 1000

    tokenize: intl
    target_language: de
    use_bpe: True
    ref: /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/IWSLT15.TED.tst2012.en-de.de
    detruecase_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/recaser/detruecase.perl
    detokenize_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/tokenizer/detokenizer.perl

    beam_search:
      beam_size: 4
      max_steps: 150
      length_penalty: True
      alpha: 0.6

Test:
  refs: [
    /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/IWSLT15.TED.tst2013.en-de.de,
    /home/zhengx/data/wmt14_adapt_dataset_share/iwslt2015/IWSLT15.TED.tst2014.en-de.de,
  ]
  output_path:
    - "/home/zhengx/output/iwslt-ende/tst2013.output"
    - "/home/zhengx/output/iwslt-ende/tst2014.output"

  save_in_multi_gpu: False
  model_path: /home/zhengx/model_save/wmt2014-ende/6000-4/loss_best_model

  tokenize: intl
  target_language: de
  use_bpe: True
  detruecase_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/recaser/detruecase.perl
  detokenize_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/tokenizer/detokenizer.perl

  batch_size: 40
  tag: translation

  beam_search:
    beam_size: 4
    max_steps: 150
    length_penalty: True
    alpha: 0.6

Record:
  training_record_path: "/home/user_data55/zhengx/record/wmt14-2-iwslt/single/layer6-head4-dim1024-drop03"
  
  model_record:
    path: /home/zhengx/model_save/wmt14-2-iwslt/single/layer6-head4-dim1024-drop03
    best_model_save:
      loss_best: False
      bleu_best: True
      save_optimizer: False
      save_lr_scheduler: False
    
    # save last checkpoint
    last_checkpoint_save:
      start_on_steps: 50000
      frequency: 2000
      save_optimizer: False
      save_lr_scheduler: False
      save_checkpoint_count: 0

visualize_file: /home/zhengx/visualize/wmt14_adapt/iwslt
