Annotation:
  device: 
  language: en-de
  dataset: wmt16 en-de, 
  what: transformer, 
  hyper_parameter: 
  log_file: 

Dataset:
  train_dataset_path:
    - "/home/zhengx/data/wmt16-ende-share/train.tsv" # bpe size 32000

  dev_dataset_path:
    - "/home/zhengx/data/wmt16-ende-share/newstest2013.tsv"

  test_dataset_path:
    - "/home/zhengx/data/wmt16-ende-share/newstest2013.tsv"
    - "/home/zhengx/data/wmt16-ende-share/newstest2014.tsv"
  
  combine_train_datasets: False
  filter_len: 200

Vocab:
  use_bpe: True
  share_bpe:
  src:
    file: "/home/zhengx/data/wmt16-ende-share/vocab"
    max_size: 32768
  trg:
    file: "/home/zhengx/data/wmt16-ende-share/vocab"
    max_size: 32768

Model:
  feature_size: 512
  feedforward_dim: 2048
  head_num: 8
  dropout_rate: 0.1
  num_layers: 6

  share_enc_dec_embedding: True
  share_decoder_embedding: True

  # generator
  generator_bias: False

# criterion kl_divergence or nll
Criterion:
  # name: nll
  # label_smoothing: 0.1
  # reduction: mean

  name: kl_divergence
  label_smoothing: 0.1
  reduction: sum

Optimizer:
  # beta2: 0.98
  # lr_scheduler:
  #   name: inverse_sqrt
  #   init_lr: 1.0e-7
  #   max_lr: 0.0007
  #   min_lr: 1.0e-9
  #   warmup_steps: 4000
  beta2: 0.998
  lr_scheduler:
    name: noam
    factor: 2.0
    warmup_steps: 8000
    model_size: 512
  grad_clip: -1.0


Train:
  use_multiple_gpu: False

  random_seed: 1234
  load_exist_model: False # load model
  model_load_path:
  load_optimizer: False  # load model and optimizer
  optimizer_path: 

  batch_size: 12000
  update_batch_count: 3
  epoch_num: 150

Validation:
  
  batch_size: 64

  loss_validation:
    start_on_steps: 1000
    frequency: 500
  
  bleu_validation:
    start_on_steps: 10000
    frequency: 1000

    tokenize: intl
    target_language: de
    use_bpe: True
    ref: /home/zhengx/data/wmt16-ende-share/newstest2013.de
    detruecase_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/recaser/detruecase.perl
    detokenize_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/tokenizer/detokenizer.perl

    beam_search:
      beam_size: 4
      max_steps: 150
      length_penalty: True
      alpha: 0.6

  # Bleu:
  #   gram: 4
  #   level: word

Test:
  refs: [
    /home/zhengx/data/wmt16-ende-share/newstest2013.de,
    /home/zhengx/data/wmt16-ende-share/newstest2014.de
  ]

  # parameter as validation
  model_path: /home/zhengx/model_save/wmt16-ende/kld-12000-3/average_model
  output_path:
    - "/home/zhengx/output/wmt16-ende/newstest2013.output"
    - "/home/zhengx/output/wmt16-ende/newstest2014.output"

  tokenize: intl
  target_language: de
  use_bpe: True
  detruecase_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/recaser/detruecase.perl
  detokenize_script: /home/user_data55/zhengx/project/DomainAdaptationForTranslation/scripts/tokenizer/detokenizer.perl

  batch_size: 24
  tag: translation

  beam_search:
    beam_size: 4
    max_steps: 150
    length_penalty: False
    alpha: 0.6


Record:
  training_record_path: "/home/user_data55/zhengx/project/record-new/wmt16-ende/kld-12000-3"
  
  model_record:

    path: /home/zhengx/model_save/wmt16-ende/kld-12000-3
    best_model_save:
      loss_best: True
      bleu_best: True
      save_optimizer: False
      save_lr_scheduler: False
    
    # save last checkpoint
    last_checkpoint_save:
      start_on_steps: 50000
      frequency: 1000
      save_optimizer: False
      save_lr_scheduler: False
      save_checkpoint_count: 5

AverageModel:
  load_path:
    -  /home/zhengx/model_save/wmt16-ende/kld-12000-3/checkpoint0/model
    -  /home/zhengx/model_save/wmt16-ende/kld-12000-3/checkpoint1/model
    -  /home/zhengx/model_save/wmt16-ende/kld-12000-3/checkpoint2/model
    -  /home/zhengx/model_save/wmt16-ende/kld-12000-3/checkpoint3/model
    -  /home/zhengx/model_save/wmt16-ende/kld-12000-3/checkpoint4/model
  save_path: /home/zhengx/model_save/wmt16-ende/kld-12000-3/average_model