Annotation:
  device: v1002-2
  language: de-en
  dataset: wmt2015 de-en, clean 50, bpe 32k, vocab 35k
  what: transformer, 
  hyper_parameter: 
  log_file: 

Dataset:
  train_dataset_path:
    - "/home/zhengx/data/WMT2015-ende-share/outdomain-ende.tsv" # bpe size 32000

  dev_dataset_path:
    - "/home/zhengx/data/WMT2015-ende-share/newstest2013.tsv"

  test_dataset_path:
    # - "/home/zhengx/data/News-Laws-deen-share/Laws-test.tsv"
    - "/home/zhengx/data/WMT2015-ende-share/newstest2013.tsv"
  
  combine_train_datasets: False
  filter_len: 100

Vocab:
  use_bpe: True
  src:
    file: "/home/zhengx/data/WMT2015-ende-share/vocab.de"
    max_size: 35000
  trg:
    file: "/home/zhengx/data/WMT2015-ende-share/vocab.en"
    max_size: 35000

Model:
  feature_size: 512
  feedforward_dim: 2048
  head_num: 8
  dropout_rate: 0.1
  num_layers: 6
  share_embedding: False

Optimizer:
  factor: 2.0
  warmup_step: 8000
  grad_clip: 1.0


Train:
  load_exist_model: False # load model
  model_load_path:

  load_optimizer: False  # load model and optimizer
  optimizer_path: 

  batch_size: 8096

  epoch_num: 50
  validation_per_steps: 1000

  # Optimizer:
    # name: adam
    # lr_rate: 0.0005
    # lr_schedule: True
    # patience: 5
    # grad_clip: 1.0
    # reset_lr_rate: False  # if load from checkpoint, maybe need reset lr_rate

  # tag: translation # translation discriminate adversarial

Validation:
  option: [loss, bleu] # bleu, loss, accuracy
  Decoding:
    beam_size: 4
    max_steps: 120

  batch_size: 80
  Bleu:
    gram: 4
    level: word

Test:
  batch_size: 40
  tag: translation
  Decoding:
    beam_size: 4
    max_steps: 100
  # parameter as validation
  model_path: /home/zhengx/model_save/wmt2015-deen/mt-transformer-2/model/best_model
  output_path:
    - "/home/zhengx/output/Education-Laws-deen-label/education.output"
    # - "/home/zhengx/output/Education-Laws-deen-label/laws.output"
    # - "../data/finetune-ende/nc-devtest2007.output"

Record:
  path: "/home/user_data55/zhengx/project/record-new/wmt2015-deen/mt-transformer-3"
  model_record_path: /home/zhengx/model_save/wmt2015-deen/mt-transformer-3
